name: Submodule Sync

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  sync:
    name: Syncing Submodules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Action
        run: |
          for module in Module*/
          do
            git -C $module checkout main && git -C $module pull &
          done

      - name: Commit update
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" \
          && git push || echo "No changes to commit"